package com.example.task.activitylog.entities;

public enum ActivityAction {
    USER_REGISTERED,

    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,
    TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED,
    TEAM_MEMBER_ROLE_UPDATED,

    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_ARCHIVED,
    TASK_DUPLICATED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED
}